skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - images/*
matrix:
  fast_finish: true
image: Previous Visual Studio 2017 #Visual Studio 2017 #use workaround image until https://github.com/appveyor/ci/issues/1404 is resolved
environment:
  matrix:
    # First build
    - DotNetRunTime: net461
    # Second build
    - DotNetRunTime: netcoreapp2.2

#---------------------------------#
#       restore nuget packages    #
#---------------------------------#
before_build:
  - cmd: dotnet restore src\Approvals.xUnit.sln
  - cmd: echo %appveyor_build_version%

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true                     # enable MSBuild parallel builds
  project: src\Approvals.xUnit.sln # path to Visual Studio project

  # MSBuild verbosity level
  verbosity: normal                  # quiet|minimal|normal|detailed

test:
  assemblies:
    only:
      - '**\*.tests.dll'

after_build:
##  7z a Approvals.xUnit-%GitVersion_MajorMinorPatch%.zip %APPVEYOR_BUILD_FOLDER%\src\Approvals.xUnit\bin\Release\*.*

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '**\*.nupkg'
    name: 'Approvals.xUnit%GitVersion_MajorMinorPatch%.nupkg'

#---------------------------------#
#     GitHub PR notifications     #
#---------------------------------#

notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: oQQNBFHTaM9998aRO2Y2Gnvz1hSdU44cQACuLaANlAusEEA2QqlWt5hw907b/IIC # encrypted token from GitHub
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  provider: NuGet
  api_key:
    secure: Wv1JZ2saKs4I3pKXRCqusGD80LJl8dIZm26qUx6pYYFFs2d3SDHPlCbJkud4NaDE # encrypted Approvals.xUnit API key
  artifact: /.*\.nupkg/
  on:
    branch: master
